=== AnthonyGuanga/Wsthevisualcode/actividad_15/Actividad15_2.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="ciudad">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[A-Za-z]{2,19}"></xs:pattern>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="codigoID">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="\d{2}-{2,5}"></xs:pattern>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="problacion">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\d{100,100000}"></xs:pattern>
                    </xs:restriction>
                </xs:simpleType>
                </xs:element>
                <xs:element name="alcalde">
                   <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nombre">
                            <xs:simpleType>
                                <xs:restriction base="xs:string"> 
                                    <xs:pattern value="[A-Za-z]{10}"></xs:pattern>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="apellidos" maxOccurs="2">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="[A-Za-z]+\s[A-Za-z]"></xs:pattern>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="edad">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:pattern value="[1-120]{18,120}"></xs:pattern>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="telefono">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:pattern value="\d34{9}"></xs:pattern>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="tarjetadecredito"></xs:element>
                        <xs:element name="correoelectronico">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="/\S+@\S+\.\S+/"></xs:pattern>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                    </xs:sequence>
                   </xs:complexType> 
                </xs:element>
                <xs:element name="funcionarios">
                    <xs:complexType>
                        <xs:sequence >
                            <xs:element name="funcionario" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="id">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="^([0-9]){10}"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="nombreApellido">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[A-Za-z]+\s[A-Za-z]{50}"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="codigoPostal">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:pattern value="[0-9]"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="fechaDeNacimiento" type="xs:date"></xs:element>
                                        <xs:element name="contraseÃ±a">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="\d\D(%,$,@,!)"></xs:pattern>
                                                    <xs:minLength value="10"></xs:minLength>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="cuentaBancaria">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="\dES {12}"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AnthonyGuanga/Wsthevisualcode/actividad_15/Actividad15.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<ciudad xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="Actividad15_2.xsd">
    <nombre>ada</nombre>
    <codigoID></codigoID>
    <problacion></problacion>
    <alcalde>
        <nombre></nombre>
        <apellidos></apellidos>
        <edad></edad>
        <telefono></telefono>
        <tarjetadecredito>
        </tarjetadecredito>
        <correoelectronico></correoelectronico>
    </alcalde>
    <funcionarios>
        <funcionario>
            <id></id>
            <nombreApellido></nombreApellido>
            <codigoPostal></codigoPostal>
            <fechaDeNacimiento></fechaDeNacimiento>
            <contraseÃ±a></contraseÃ±a>
            <cuentaBancaria></cuentaBancaria>
        </funcionario>
    </funcionarios>
</ciudad>
