<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE videojuego[
<!ELEMENT videojuego (Nombre, Fecha_de_creacion, Nota, programadores+, Compania, Web_referencia?)>

<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Fecha_de_creacion (#PCDATA)>
<!ELEMENT Nota (#PCDATA)>
<!ELEMENT Web_referencia (#PCDATA)>
<!ELEMENT programadores (Programador+)>

<!ATTLIST videojuego id CDATA #REQUIRED>

<!ELEMENT Programador (Nombre, DNI, sudonimo, Fecha_de_nacimiento, Direccion)>
<!ELEMENT DNI (#PCDATA)>
<!ELEMENT sudonimo (#PCDATA)>
<!ELEMENT Fecha_de_nacimiento (#PCDATA)>
<!ELEMENT Direccion (tipo_de_via, Nombre_de_la_via, Codigo_postal, Pais)>
<!ELEMENT tipo_de_via (#PCDATA)>
<!ELEMENT Nombre_de_la_via (#PCDATA)>
<!ELEMENT Codigo_postal (#PCDATA)>
<!ELEMENT Pais (#PCDATA)>

<!ATTLIST Programador id CDATA #REQUIRED>

<!ATTLIST Compania id CDATA >

<!ELEMENT Compania (Nombre, NIF)>
<!ELEMENT NIF (#PCDATA)>

]>
<videojuego id="22656">
    <Nombre>Cult of the Lamb</Nombre>
    <Fecha_de_creacion>10 de junio de 2022</Fecha_de_creacion>
    <Nota>9/10</Nota>
    <programadores> 
        <Programador id="595265264965">
            <Nombre>Felipe Garcia</Nombre>
            <DNI>59595965985</DNI> 
            <sudonimo>uchija69</sudonimo> 
            <Fecha_de_nacimiento>2000/01/17</Fecha_de_nacimiento>
            <Direccion>
                <tipo_de_via>Segriá, Maials País</tipo_de_via>
                <Nombre_de_la_via>C-12 eje del Ebro</Nombre_de_la_via>
                <Codigo_postal>41323</Codigo_postal> 
                <Pais>España</Pais> 
            </Direccion>
        </Programador>

        <Programador id="595265445"> 
            <Nombre>Alfredo Martines</Nombre>
            <DNI>4644846352</DNI> 
            <sudonimo>Elpollagrnade</sudonimo> 
            <Fecha_de_nacimiento>1976/05/13</Fecha_de_nacimiento>
            <Direccion>  
                <tipo_de_via>Baztan-Bidasoa</tipo_de_via>
                <Nombre_de_la_via>Carretera de Maya</Nombre_de_la_via>
                <Codigo_postal>43198</Codigo_postal> 
                <Pais>España</Pais> 
            </Direccion>
        </Programador>

        <Programador id="595265464">
            <Nombre>Paul Magro</Nombre>
            <DNI>4854948484</DNI> 
            <sudonimo>Elputomamo</sudonimo> 
            <Fecha_de_nacimiento>2003/03/27</Fecha_de_nacimiento>
            <Direccion> 
                <tipo_de_via>Caserio Anita Cepeda s/n.</tipo_de_via>
                <Nombre_de_la_via>Murcia, Altiplano</Nombre_de_la_via>
                <Codigo_postal>387452927</Codigo_postal> 
                <Pais>España</Pais> 
            </Direccion>
        </Programador>
    </programadores>
        
   <Compania id="0897878">
        <Nombre>Massive Monster</Nombre> 
        <NIF>4594804415</NIF>
        <Direccion> 
            <tipo_de_via>100 FATHER MEL ST</tipo_de_via>
            <Nombre_de_la_via>PITI GU</Nombre_de_la_via>
            <Codigo_postal>96915</Codigo_postal> 
            <Pais>USA</Pais> 
        </Direccion> 
    </Compania>
    <Web_referencia>https://www.cultofthelamb.com</Web_referencia>
</videojuego>
