=== AnthonyGuanga/Wsthevisualcode/actividad_13/Actividad.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="empresa">
        <xs:complexType>
             <xs:sequence>
                <xs:element name="NIF"></xs:element>
                <xs:element name="espaÃ±ola" type="xs:boolean"></xs:element>
                <xs:element name="capitalsocial"></xs:element>
                <xs:element name="direccion">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="tipodevia"></xs:element>
                            <xs:element name="nombredevia"></xs:element>
                            <xs:element name="CP"></xs:element>
                            <xs:element name="pais"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="empleados" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="empleado"></xs:element>
                            <xs:element name="nombre"></xs:element>
                            <xs:element name="apellido"></xs:element>
                            <xs:element name="apellido2"></xs:element>
                            <xs:element name="DNI"></xs:element>
                            <xs:element name="extranjero" type="xs:boolean"></xs:element>
                            <xs:element name="fechadenacimiento"></xs:element>
                            <xs:element name="salario"></xs:element>
                            <xs:element name="direcciones" >
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="direccion"></xs:element>
                                        <xs:element name="pais"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="direcciones2" >
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="direccion"></xs:element>
                                        <xs:element name="pais"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="estacasado" type="xs:boolean"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="fechadecreacion" type="xs:date"></xs:attribute>
            <xs:attribute name="pais" type="xs:string" fixed="espania"></xs:attribute>
            <xs:attribute name="moneda" type="xs:string" ></xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AnthonyGuanga/Wsthevisualcode/actividad_13/Actividad13-1.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<empresa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Actividad.xsd">
  <NIF>4498449595 </NIF>
  <española>true</española>
  <capitalsocial> euro </capitalsocial>
  <direccion>
      <tipodevia>calle nueva </tipodevia>
      <nombredevia> oreste</nombredevia>
      <CP>45 </CP>
      <pais> espñol</pais>
  </direccion>
  <empleados>
    <empleado> juan</empleado>
    <nombre> alberto </nombre>
    <apellido> juan</apellido>
    <apellido2>alberto</apellido2>
    <DNI>8656595</DNI>
    <extranjero>true</extranjero>
    <fechadenacimiento> 01/23/2000</fechadenacimiento>
    <salario> 3000 </salario>
    <direcciones>
      <direccion> calle de luz</direccion>
      <pais> españia</pais>
    </direcciones>
    <direcciones2>
      <direccion> calle oeste</direccion>
      <pais> españia</pais>
    </direcciones2>
    <estacasado>true</estacasado>
  </empleados>
</empresa>
