=== AnthonyGuanga/Wsthevisualcode/actividad_13/Actividad13-4.dtd
<!ELEMENT empresa (nombre, NIF, esEspaniola, capital_social, direccion_empresa, empleados)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT NIF (#PCDATA)>
  <!ELEMENT esEspaniola (#PCDATA)>
  <!ELEMENT capital_social (#PCDATA)>
 
  <!ELEMENT direccion_empresa (tipo_via, nombre_via, CP, pais)>
  <!ELEMENT tipo_via (#PCDATA)>
  <!ELEMENT nombre_via (#PCDATA)>
  <!ELEMENT CP (#PCDATA)>
  <!ELEMENT pais (#PCDATA)>
  
  <!ELEMENT empleados (empleado+)>
  <!ELEMENT empleado (nombre, apellido+, DNI, extranjero, fecha_nacimiento, salario, direccion_empleado, casado?)>
  <!ELEMENT casado (#PCDATA)>
  <!ELEMENT apellido (#PCDATA)>
  <!ELEMENT DNI (#PCDATA)>
  <!ELEMENT extranjero (#PCDATA)>
  <!ELEMENT fecha_nacimiento (#PCDATA)>
  <!ELEMENT salario (#PCDATA)>
  <!ELEMENT direccion_empleado (cadena, pais)>
  <!ELEMENT cadena (#PCDATA)>

=== AnthonyGuanga/Wsthevisualcode/actividad_13/Actividad13-4-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empresa SYSTEM "Actividad13-4.dtd">
<empresa>
    <nombre>Empresa ABC</nombre>
    <NIF>123456789A</NIF>
    <esEspaniola>true</esEspaniola>
    <capital_social>25000</capital_social>
    <direccion_empresa>
        <tipo_via>Calle</tipo_via>
        <nombre_via>Gran Vía</nombre_via>
        <CP>28001</CP>
        <pais>España</pais>
    </direccion_empresa>
    <empleados>
        <empleado>
            <nombre>Juan</nombre>
            <apellido>García</apellido>
            <apellido>Pérez</apellido>
            <DNI>12345678A</DNI>
            <extranjero>false</extranjero>
            <fecha_nacimiento>1990-05-15</fecha_nacimiento>
            <salario>2500.00</salario>
            <direccion_empleado>
                <cadena>Calle Mayor 12, Madrid</cadena>
                <pais>España</pais>
            </direccion_empleado>
            <casado>true</casado>
        </empleado>
        <empleado>
            <nombre>Maria</nombre>
            <apellido>López</apellido>
            <apellido>García</apellido>
            <DNI>87654321B</DNI>
            <extranjero>false</extranjero>
            <fecha_nacimiento>1985-10-20</fecha_nacimiento>
            <salario>3000.00</salario>
            <direccion_empleado>
                <cadena>Calle Sol 5, Barcelona</cadena>
                <pais>España</pais>
            </direccion_empleado>
            <casado>false</casado>
        </empleado>
    </empleados>
</empresa>
